var error 

try {
  error = customError();
} catch(cError) {
  error = cError;
}
